name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Versionamient
    - name: Git semantic version
      uses: PaulHatch/semantic-version@4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prereleases${increment}"
      id: version
    # Autenticar en docker hub
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION !!!!!!!!!"
        echo "Fin login"
    # Construir la imagen
    - name: Build docker image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build -t pateli/docker-graphql:$NEW_VERSION .
        docker build -t pateli/docker-graphql:latest .
    # Push
    - name: Push docker image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker push pateli/docker-graphql:$NEW_VERSION
        docker push pateli/docker-graphql:latest
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
